### ISSUE TITLE
What are the changes ?

### ISSUE THREAD

**Issue by smrsan76** [mehrad77/mehrad-hexo-cactus#1]
I have seen it, before ...
It's exactly like this hexo theme, ([here](https://probberechts.github.io/hexo-theme-cactus/)).
What are the changes you have made on this [repo](https://github.com/probberechts/hexo-theme-cactus/) ??

( I already know that it's your version/copy/fork of cactus theme ... )

**Comment by mehrad77** [comment]
Well in [here](https://github.com/mehrad77/mehrad77.github.io-dev) I used four different Hexo directories for four separated languages. (I know it's not the best way, but It's ok for my needs)
So this version is just for syncing them with my parameters and changes. that's it.

But I have some plans to add RTL Support. I'll probably make a pull request to main repo for that.

**Comment by mehrad77** [comment]
btw you can see changes here: https://github.com/mehrad77/mehrad-hexo-cactus/commit/dee28811d36b2009f0479759b86e03ed7c127729
